src/Entity/ArticleAmount.php
<?php

namespace App\Entity;

use App\Repository\ArticleAmountRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleAmountRepository::class)]
class ArticleAmount
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'articleAmounts')]
    private ?ArticleWarehouse $article_warehouse = null;

    #[ORM\Column(nullable: true)]
    private ?int $amount = null;

    #[ORM\Column(nullable: true)]
    private ?int $value = null;

    #[ORM\Column(nullable: true)]
    private ?int $tax = null;

    #[ORM\ManyToOne(inversedBy: 'articleAmounts')]
    private ?Bill $bill = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticleWarehouse(): ?ArticleWarehouse
    {
        return $this->article_warehouse;
    }

    public function setArticleWarehouse(?ArticleWarehouse $article_warehouse): static
    {
        $this->article_warehouse = $article_warehouse;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(?int $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(?int $value): static
    {
        $this->value = $value;

        return $this;
    }

    public function getTax(): ?int
    {
        return $this->tax;
    }

    public function setTax(?int $tax): static
    {
        $this->tax = $tax;

        return $this;
    }

    public function getBill(): ?Bill
    {
        return $this->bill;
    }

    public function setBill(?Bill $bill): static
    {
        $this->bill = $bill;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_admin = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_company = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isIsAdmin(): ?bool
    {
        return $this->is_admin;
    }

    public function setIsAdmin(?bool $is_admin): static
    {
        $this->is_admin = $is_admin;

        return $this;
    }

    public function isIsCompany(): ?bool
    {
        return $this->is_company;
    }

    public function setIsCompany(?bool $is_company): static
    {
        $this->is_company = $is_company;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Repository\BillRepository;
use ContainerXQhQqEd\getCache_SecurityIsGrantedAttributeExpressionLanguageService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils, BillRepository $billRepository): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        $allBills = $billRepository->findAll();
        $bills = $allBills;
        if (count($allBills) > 5)
        {
            $bills = array_slice($allBills, count($allBills) - 5, 5);
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error, 'bills' => $bills]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route(path: '/determine/user', name: 'determine_user')]
    public function determineUser()
    {
        $user = $this->getUser();
        if ($user->isIsAdmin())
        {
            return $this->redirectToRoute('admin_all_companies');
        }
        else if ($user->isIsCompany())
        {
            return $this->redirectToRoute('company');
        }
        else
        {
            return $this->redirectToRoute('customer_all_companies');
        }
    }
}

templates/security/login.html.twig
{% trans_default_domain 'app' %}

{% extends 'base.html.twig' %}

{% block body %}
    <div class="login-container">
        <div class="login-form">
            <form method="post">
                <div class="login-form-content">
                    {% if error %}
                        <div class="alert alert-danger text-center">{{ 'login.invalid-credentials'|trans }}</div>
                    {% endif %}

                    {% if app.user %}
                        <div class="mb-3">
                            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
                        </div>
                    {% endif %}

                    <br>
                    <br>
                    <br>
                    <h1 class="h3 font-weight-normal">{{ 'login.message'|trans }}</h1>
                    <label class="mt-3" for="inputUsername">{{ 'form.element.username'|trans }}</label>
                    <input type="text" value="{{ last_username }}" name="username" id="inputUsername" class="form-control" autocomplete="username" required autofocus>
                    <label class="mt-3" for="inputPassword">{{ 'form.element.password'|trans }}</label>
                    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

                    <input type="hidden" name="_csrf_token"
                           value="{{ csrf_token('authenticate') }}"
                    >

                    <button class="btn btn-lg btn-primary mt-3" type="submit">
                        {{ 'form.element.sign-in'|trans }}
                    </button>

                    <p class="mt-3">{{ 'general.no-account'|trans }} <a href="{{ path('register_company') }}">{{ 'general.register'|trans }}</a></p>

                    <br>

                    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner" style="border-radius: 10px;">
                            {% set index = 0 %}
                            {% for bill in bills %}
                            <div class="carousel-item {% if index == 0 %}active{% endif %}" style="background: #fff!important; color: #000!important; max-height: 300px; height: 300px; overflow-y: scroll; padding: 20px 45px;">
                                <h5 class="text-center">{{ bill.company.title }} - {{ bill.date|date('d-m-Y H:i:s') }}</h5>
                                <hr>
                                <ul>
                                    {% set total = 0 %}
                                    {% for articleAmount in bill.articleAmounts %}
                                        <li class="ms-3">{{ articleAmount.articleWarehouse.article.title }} x {{ articleAmount.amount }} : <b>{{ articleAmount.value }} RSD</b></li>
                                        {% set total = total + articleAmount.value * articleAmount.amount %}
                                    {% endfor %}
                                </ul>
                                <hr>
                                <h5>{{ 'general.total'|trans }}: <b>{{ total }} RSD</b></h5>
                            </div>
                            {% set index = index + 1 %}
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true" style="color: #000;"><i class="fa-solid fa-arrow-left"></i></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true" style="color: #000;"><i class="fa-solid fa-arrow-right"></i></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="login-side">
            <img src="/assets/images/login-bg.jpg">
        </div>
    </div>
{% endblock %}