src/Entity/Bill.php
<?php

namespace App\Entity;

use App\Repository\BillRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BillRepository::class)]
class Bill
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $payed = null;

    #[ORM\ManyToOne(inversedBy: 'bills')]
    private ?PayingType $paying_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_name = null;

    #[ORM\ManyToOne(inversedBy: 'bills')]
    private ?Customer $customer = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $customer_id_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slip_bill_number = null;

    #[ORM\ManyToOne(inversedBy: 'bills')]
    private ?Partner $partner = null;

    #[ORM\OneToMany(targetEntity: ArticleAmount::class, mappedBy: 'bill')]
    private Collection $articleAmounts;

    #[ORM\ManyToOne(inversedBy: 'bills')]
    private ?Company $company = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date = null;

    public function __construct()
    {
        $this->articleAmounts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPayed(): ?int
    {
        return $this->payed;
    }

    public function setPayed(?int $payed): static
    {
        $this->payed = $payed;

        return $this;
    }

    public function getPayingType(): ?PayingType
    {
        return $this->paying_type;
    }

    public function setPayingType(?PayingType $paying_type): static
    {
        $this->paying_type = $paying_type;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function getCustomerIdNumber(): ?string
    {
        return $this->customer_id_number;
    }

    public function setCustomerIdNumber(?string $customer_id_number): static
    {
        $this->customer_id_number = $customer_id_number;

        return $this;
    }

    public function getSlipBillNumber(): ?string
    {
        return $this->slip_bill_number;
    }

    public function setSlipBillNumber(?string $slip_bill_number): static
    {
        $this->slip_bill_number = $slip_bill_number;

        return $this;
    }

    public function getPartner(): ?Partner
    {
        return $this->partner;
    }

    public function setPartner(?Partner $partner): static
    {
        $this->partner = $partner;

        return $this;
    }

    /**
     * @return Collection<int, ArticleAmount>
     */
    public function getArticleAmounts(): Collection
    {
        return $this->articleAmounts;
    }

    public function addArticleAmount(ArticleAmount $articleAmount): static
    {
        if (!$this->articleAmounts->contains($articleAmount)) {
            $this->articleAmounts->add($articleAmount);
            $articleAmount->setBill($this);
        }

        return $this;
    }

    public function removeArticleAmount(ArticleAmount $articleAmount): static
    {
        if ($this->articleAmounts->removeElement($articleAmount)) {
            // set the owning side to null (unless already changed)
            if ($articleAmount->getBill() === $this) {
                $articleAmount->setBill(null);
            }
        }

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

}

src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompanyRepository::class)]
class Company
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_name = null;

    #[ORM\ManyToOne]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $post_code = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $street = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tin = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $identification_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_url = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_active = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_configured = null;

    #[ORM\Column(nullable: true)]
    private ?bool $vat = null;

    #[ORM\OneToMany(targetEntity: BankAccount::class, mappedBy: 'company')]
    private Collection $bankAccounts;

    #[ORM\OneToMany(targetEntity: Warehouse::class, mappedBy: 'company')]
    private Collection $warehouses;

    #[ORM\OneToMany(targetEntity: CashRegister::class, mappedBy: 'company')]
    private Collection $cashRegisters;

    #[ORM\ManyToMany(targetEntity: Partner::class, mappedBy: 'company')]
    private Collection $partners;

    #[ORM\Column(nullable: true)]
    private ?bool $editedByAdmin = null;

    #[ORM\OneToMany(targetEntity: Bill::class, mappedBy: 'company')]
    private Collection $bills;

    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'company')]
    private Collection $articles;

    #[ORM\ManyToOne(inversedBy: 'companies')]
    private ?CompanyCategory $category = null;

    #[ORM\ManyToOne(inversedBy: 'companies')]
    private ?ActiviyCode $activity_code = null;

    #[ORM\OneToMany(targetEntity: PayingDaysRebate::class, mappedBy: 'company')]
    private Collection $payingDaysRebates;

    #[ORM\OneToMany(targetEntity: TableSchedule::class, mappedBy: 'company')]
    private Collection $tableSchedules;

    #[ORM\OneToMany(targetEntity: ArticleCategory::class, mappedBy: 'company')]
    private Collection $articleCategories;

    public function __construct()
    {
        $this->bankAccounts = new ArrayCollection();
        $this->warehouses = new ArrayCollection();
        $this->cashRegisters = new ArrayCollection();
        $this->partners = new ArrayCollection();
        $this->bills = new ArrayCollection();
        $this->articles = new ArrayCollection();
        $this->payingDaysRebates = new ArrayCollection();
        $this->tableSchedules = new ArrayCollection();
        $this->articleCategories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getPostCode(): ?string
    {
        return $this->post_code;
    }

    public function setPostCode(?string $post_code): static
    {
        $this->post_code = $post_code;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(?string $number): static
    {
        $this->number = $number;

        return $this;
    }

    public function getTin(): ?string
    {
        return $this->tin;
    }

    public function setTin(?string $tin): static
    {
        $this->tin = $tin;

        return $this;
    }

    public function getIdentificationNumber(): ?string
    {
        return $this->identification_number;
    }

    public function setIdentificationNumber(?string $identification_number): static
    {
        $this->identification_number = $identification_number;

        return $this;
    }

    public function getLogoUrl(): ?string
    {
        return $this->logo_url;
    }

    public function setLogoUrl(?string $logo_url): static
    {
        $this->logo_url = $logo_url;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function isIsConfigured(): ?bool
    {
        return $this->is_configured;
    }

    public function setIsConfigured(?bool $is_configured): static
    {
        $this->is_configured = $is_configured;

        return $this;
    }

    public function isVat(): ?bool
    {
        return $this->vat;
    }

    public function setVat(?bool $vat): static
    {
        $this->vat = $vat;

        return $this;
    }

    /**
     * @return Collection<int, BankAccount>
     */
    public function getBankAccounts(): Collection
    {
        return $this->bankAccounts;
    }

    public function addBankAccount(BankAccount $bankAccount): static
    {
        if (!$this->bankAccounts->contains($bankAccount)) {
            $this->bankAccounts->add($bankAccount);
            $bankAccount->setCompany($this);
        }

        return $this;
    }

    public function removeBankAccount(BankAccount $bankAccount): static
    {
        if ($this->bankAccounts->removeElement($bankAccount)) {
            // set the owning side to null (unless already changed)
            if ($bankAccount->getCompany() === $this) {
                $bankAccount->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Warehouse>
     */
    public function getWarehouses(): Collection
    {
        return $this->warehouses;
    }

    public function addWarehouse(Warehouse $warehouse): static
    {
        if (!$this->warehouses->contains($warehouse)) {
            $this->warehouses->add($warehouse);
            $warehouse->setCompany($this);
        }

        return $this;
    }

    public function removeWarehouse(Warehouse $warehouse): static
    {
        if ($this->warehouses->removeElement($warehouse)) {
            // set the owning side to null (unless already changed)
            if ($warehouse->getCompany() === $this) {
                $warehouse->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CashRegister>
     */
    public function getCashRegisters(): Collection
    {
        return $this->cashRegisters;
    }

    public function addCashRegister(CashRegister $cashRegister): static
    {
        if (!$this->cashRegisters->contains($cashRegister)) {
            $this->cashRegisters->add($cashRegister);
            $cashRegister->setCompany($this);
        }

        return $this;
    }

    public function removeCashRegister(CashRegister $cashRegister): static
    {
        if ($this->cashRegisters->removeElement($cashRegister)) {
            // set the owning side to null (unless already changed)
            if ($cashRegister->getCompany() === $this) {
                $cashRegister->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Partner>
     */
    public function getPartners(): Collection
    {
        return $this->partners;
    }

    public function addPartner(Partner $partner): static
    {
        if (!$this->partners->contains($partner)) {
            $this->partners->add($partner);

src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $id_number = null;

    #[ORM\OneToMany(targetEntity: Bill::class, mappedBy: 'customer')]
    private Collection $bills;

    public function __construct()
    {
        $this->bills = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getIdNumber(): ?string
    {
        return $this->id_number;
    }

    public function setIdNumber(?string $id_number): static
    {
        $this->id_number = $id_number;

        return $this;
    }

    /**
     * @return Collection<int, Bill>
     */
    public function getBills(): Collection
    {
        return $this->bills;
    }

    public function addBill(Bill $bill): static
    {
        if (!$this->bills->contains($bill)) {
            $this->bills->add($bill);
            $bill->setCustomer($this);
        }

        return $this;
    }

    public function removeBill(Bill $bill): static
    {
        if ($this->bills->removeElement($bill)) {
            // set the owning side to null (unless already changed)
            if ($bill->getCustomer() === $this) {
                $bill->setCustomer(null);
            }
        }

        return $this;
    }
}

templates/customer/analytic.html.twig
{% extends 'customer/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
    {% set totalValue = 0 %}
    <div class="container py-5">
        <a class="back" href="{{ path('customer_analytics') }}"><i class="fa-solid fa-arrow-left me-2"></i>{{ 'general.back'|trans }}</a>
        <hr>
        <div class="row">
            <div class="col-12 col-md-4">
                <h1>{{ 'bill.info'|trans }}</h1>
                <ul class="bill-info-list">
                    <li>{{ ('analytics.table.company-title'|trans)~': '~bill.company.title }}</li>
                    <li>{{ ('analytics.table.date'|trans)~': '~bill.date|date('d.m.Y.') }}</li>
                    <li>{{ ('analytics.table.payment-method'|trans)~': '~('payment-method.' ~ bill.payingType.title)|trans }}</li>
                    {% if bill.payingType.title == 'cash' %}

                    {% elseif bill.payingType.title == 'check' %}
                        <li>{{ ('form.element.first-name'|trans)~': '~bill.firstName }}</li>
                        <li>{{ ('form.element.last-name'|trans)~': '~bill.lastName }}</li>
                    {% else %}
                        <li>{{ ('form.element.slip-bill'|trans)~': '~bill.slipBillNumber }}</li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-12 col-md-8">
                <h1>{{ 'bill.articles'|trans }}</h1>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">{{ 'analytics.table.article'|trans }}</th>
                            <th scope="col">{{ 'analytics.table.amount'|trans }}</th>
                            <th scope="col">{{ 'analytics.table.value'|trans }} [RSD]</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for article in articles %}
                            <tr>
                                <td>{{ article.title }}</td>
                                <td>{{ article.amount }} </td>
                                <td>{{ article.value }}</td>
                                {% set totalValue = totalValue + article.value * article.amount %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p style="font-size: 20px;">{{ ('general.total-value'|trans)~': ' }}<b>{{ totalValue }} RSD</b></p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/customer/analytics.html.twig
{% extends 'customer/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
    <div class="container py-5">
        <div class="row">
            <div class="col-12 col-lg-6">
                <h2>{{ 'analytics.customer.bills'|trans }}</a></h2>
                <div class="table-responsive">
                    {% if table %}
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">{{ 'analytics.table.company-title'|trans }}</th>
                                <th scope="col">{{ 'analytics.table.warehouse-title'|trans }}</th>
                                <th scope="col">{{ 'analytics.table.value'|trans }} [RSD]</th>
                                <th scope="col">{{ 'analytics.table.payment-method'|trans }}</th>
                                <th scope="col">{{ 'general.details'|trans }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for row in table %}
                                <tr>
                                    <td>{{ row.company }}</td>
                                    <td>{{ row.warehouse }} </td>
                                    <td>{{ row.val }}</td>
                                    <td>{{ ('payment-method.'~row.pay)|trans }}</td>
                                    <td><a href="{{ path('customer_analytic', {id: row.id}) }}" class="btn btn-info"><i class="text-light fa-solid fa-circle-info"></i></a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        {{ 'analytics.no-data'|trans }}
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-lg-6">
                <h2 class="text-center">{{ 'analytics.customer.charts'|trans }}</a></h2>
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-12">
                        <canvas id="currentMonth"></canvas>
                    </div>
                    <div class="col-12 col-md-6 col-lg-12">
                        <canvas id="lastYear"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        let ctxCurrentMonth = document.getElementById("currentMonth").getContext("2d");
        let ctxLastYear = document.getElementById("lastYear").getContext("2d");

        new Chart(ctxCurrentMonth, {
            type: 'bar',
            data: {
                labels: [{{ labelsCurrentMonth|join(',')|raw }}],
                datasets: [{
                    data: [{{ dataCurrentMonth|join(',') }}],
                    borderWidth: 0,
                    backgroundColor: ['#1e90ff']
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        display: false
                    },
                    title: {
                        display: true,
                        text: '{{ "chart.amount-payed.this-month"|trans }}'
                    }
                }
            }
        });

        new Chart(ctxLastYear, {
            type: 'bar',
            data: {
                labels: [{{ (labelsLastYear)|join(',')|raw }}],
                datasets: [{
                    data: [{{ dataLastYear|join(',') }}],
                    borderWidth: 0,
                    backgroundColor: ['#ffa500']
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        display: false
                    },
                    title: {
                        display: true,
                        text: '{{ "chart.amount-payed.last-year"|trans }}'
                    }
                }
            }
        });
    </script>
{% endblock %}

templates/customer/base.html.twig
{% extends 'base.html.twig' %}

{% trans_default_domain 'app' %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-5">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-user me-2"></i>{{ user.username }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a href="{{ path('change_password') }}" class="dropdown-item" href="#"><i class="fa-solid fa-lock me-2"></i> {{ 'general.change-password'|trans|lower }}</a></li>
                    <li><a href="{{ path('app_logout') }}" class="dropdown-item" href="#"><i class="fa-solid fa-right-from-bracket me-2"></i>{{ 'general.logout'|trans }}</a></li>
                </ul>
            </li>
        </ul>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item ms-4">
                    <a class="nav-link" href="{{ path('customer_all_companies') }}"><i class="fa-solid fa-building me-2"></i>{{ 'customer.nav.companies'|trans }}</a>
                </li>
                <li class="nav-item ms-4">
                    <a class="nav-link" href="{{ path('customer_analytics') }}"><i class="fa-solid fa-chart-pie me-2"></i>{{ 'customer.nav.analytics'|trans }}</a>
                </li>
            </ul>

        </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% include 'footer.html.twig' %}
{% endblock %}

templates/customer/change-password.html.twig
{% extends 'customer/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
    <div class="container-fluid d-flex justify-content-center">
        <div class="admin-customer-registration-container">
            <div class="company-registration-form">
                <h3>{{ 'general.change-password'|trans }}</h3>
                <hr>
                {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}

                {{ form_end(form) }}
            </div>
        </div>
    </div>

{% endblock %}

templates/customer/companies.html.twig
{% extends 'customer/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
<div class="container py-5">
    <h2>{{ 'company.active-companies'|trans }}</a></h2>
    <div>
        <div class="table-responsive">
            {% if activeCompanies %}
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">{{ 'company.table.title'|trans }}</th>
                        <th scope="col">{{ 'company.table.owner'|trans }}</th>
                        <th scope="col">{{ 'company.table.address'|trans }}</th>
                        <th scope="col">{{ 'company.table.post-code'|trans }}</th>
                        <th scope="col">{{ 'company.table.city'|trans }}</th>
                        <th scope="col">{{ 'company.table.country'|trans }}</th>
                        <th scope="col">{{ 'general.details'|trans }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for company in activeCompanies %}
                        <tr>
                            <td>{{ company.title }}</td>
                            <td>{{ company.firstName }} {{ company.lastName }}</td>
                            <td>{{ company.street }} {{ company.number }}</td>
                            <td>{{ company.postCode }} </td>
                            <td>{{ company.city }}</td>
                            <td>{{ company.country }}</td>
                            <td><a href="{{ path('customer_company', {id: company.id}) }}" class="btn btn-info"><i class="text-light fa-solid fa-circle-info"></i></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                {{ 'general.empty-category'|trans }}
            {% endif %}
        </div>
    </div>
    {% if totalPages > 1 %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a class="page-link {% if currentPage == 1 %} disabled {% endif %}" href="{{ path('customer_all_companies', {page: currentPage - 1}) }}"><i class="fa-solid fa-square-caret-left"></i></a></li>
                {% for page in 1..totalPages %}
                    <li class="page-item"><a class="page-link {% if page == currentPage %} active {% endif %}" href="{{ path('customer_all_companies', {page: page}) }}">{{ page }}</a></li>
                {% endfor %}
                <li class="page-item"><a class="page-link {% if currentPage == totalPages %} disabled {% endif %}" href="{{ path('customer_all_companies', {page: currentPage + 1}) }}"><i class="fa-solid fa-square-caret-right"></i></a></li>
            </ul>
        </nav>
    {% endif %}
</div>
{% endblock %}

templates/customer/company.html.twig
{% extends 'customer/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
<div class="container py-5">
    <a class="back" href="{{ path('customer_all_companies') }}"><i class="fa-solid fa-arrow-left me-2"></i>{{ 'general.back'|trans }}</a>
    <hr>
    {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
    <div class="row pb-5">
        <div class="col-8 col-md-4">
            <label for="articles_search_form_title">{{ 'form.element.title'|trans }}</label>
            {{ form_row(form.title, {attr: {class: 'form-control'}}) }}
        </div>
        <div class="col-2">
            {{ form_row(form.submit, {attr: {class: 'btn btn-lg btn-primary mt-3'}}) }}

        </div>
    </div>
    {{ form_end(form) }}
    <div class="row">
        {% if table %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">{{ 'form.element.title'|trans }}</th>
                        <th scope="col">{{ 'review.table.producer'|trans }}</th>
                        <th scope="col">{{ 'review.table.min-price'|trans }}</th>
                        <th scope="col">{{ 'review.table.available-at'|trans }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for row in table %}
                        <tr>
                            <td>{{ row.title }}</td>
                            <td>{{ row.producer }}</td>
                            <td>{{ row.min_price }}</td>
                            <td>{{ row.warehouses }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p style="font-size: 20px;">
                {{ 'general.no-articles-data'|trans }}
            </p>
        {% endif %}
    </div>
</div>
{% endblock %}