src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompanyRepository::class)]
class Company
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_name = null;

    #[ORM\ManyToOne]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $post_code = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $street = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tin = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $identification_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_url = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_active = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_configured = null;

    #[ORM\Column(nullable: true)]
    private ?bool $vat = null;

    #[ORM\OneToMany(targetEntity: BankAccount::class, mappedBy: 'company')]
    private Collection $bankAccounts;

    #[ORM\OneToMany(targetEntity: Warehouse::class, mappedBy: 'company')]
    private Collection $warehouses;

    #[ORM\OneToMany(targetEntity: CashRegister::class, mappedBy: 'company')]
    private Collection $cashRegisters;

    #[ORM\ManyToMany(targetEntity: Partner::class, mappedBy: 'company')]
    private Collection $partners;

    #[ORM\Column(nullable: true)]
    private ?bool $editedByAdmin = null;

    #[ORM\OneToMany(targetEntity: Bill::class, mappedBy: 'company')]
    private Collection $bills;

    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'company')]
    private Collection $articles;

    #[ORM\ManyToOne(inversedBy: 'companies')]
    private ?CompanyCategory $category = null;

    #[ORM\ManyToOne(inversedBy: 'companies')]
    private ?ActiviyCode $activity_code = null;

    #[ORM\OneToMany(targetEntity: PayingDaysRebate::class, mappedBy: 'company')]
    private Collection $payingDaysRebates;

    #[ORM\OneToMany(targetEntity: TableSchedule::class, mappedBy: 'company')]
    private Collection $tableSchedules;

    #[ORM\OneToMany(targetEntity: ArticleCategory::class, mappedBy: 'company')]
    private Collection $articleCategories;

    public function __construct()
    {
        $this->bankAccounts = new ArrayCollection();
        $this->warehouses = new ArrayCollection();
        $this->cashRegisters = new ArrayCollection();
        $this->partners = new ArrayCollection();
        $this->bills = new ArrayCollection();
        $this->articles = new ArrayCollection();
        $this->payingDaysRebates = new ArrayCollection();
        $this->tableSchedules = new ArrayCollection();
        $this->articleCategories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getPostCode(): ?string
    {
        return $this->post_code;
    }

    public function setPostCode(?string $post_code): static
    {
        $this->post_code = $post_code;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(?string $number): static
    {
        $this->number = $number;

        return $this;
    }

    public function getTin(): ?string
    {
        return $this->tin;
    }

    public function setTin(?string $tin): static
    {
        $this->tin = $tin;

        return $this;
    }

    public function getIdentificationNumber(): ?string
    {
        return $this->identification_number;
    }

    public function setIdentificationNumber(?string $identification_number): static
    {
        $this->identification_number = $identification_number;

        return $this;
    }

    public function getLogoUrl(): ?string
    {
        return $this->logo_url;
    }

    public function setLogoUrl(?string $logo_url): static
    {
        $this->logo_url = $logo_url;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function isIsConfigured(): ?bool
    {
        return $this->is_configured;
    }

    public function setIsConfigured(?bool $is_configured): static
    {
        $this->is_configured = $is_configured;

        return $this;
    }

    public function isVat(): ?bool
    {
        return $this->vat;
    }

    public function setVat(?bool $vat): static
    {
        $this->vat = $vat;

        return $this;
    }

    /**
     * @return Collection<int, BankAccount>
     */
    public function getBankAccounts(): Collection
    {
        return $this->bankAccounts;
    }

    public function addBankAccount(BankAccount $bankAccount): static
    {
        if (!$this->bankAccounts->contains($bankAccount)) {
            $this->bankAccounts->add($bankAccount);
            $bankAccount->setCompany($this);
        }

        return $this;
    }

    public function removeBankAccount(BankAccount $bankAccount): static
    {
        if ($this->bankAccounts->removeElement($bankAccount)) {
            // set the owning side to null (unless already changed)
            if ($bankAccount->getCompany() === $this) {
                $bankAccount->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Warehouse>
     */
    public function getWarehouses(): Collection
    {
        return $this->warehouses;
    }

    public function addWarehouse(Warehouse $warehouse): static
    {
        if (!$this->warehouses->contains($warehouse)) {
            $this->warehouses->add($warehouse);
            $warehouse->setCompany($this);
        }

        return $this;
    }

    public function removeWarehouse(Warehouse $warehouse): static
    {
        if ($this->warehouses->removeElement($warehouse)) {
            // set the owning side to null (unless already changed)
            if ($warehouse->getCompany() === $this) {
                $warehouse->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CashRegister>
     */
    public function getCashRegisters(): Collection
    {
        return $this->cashRegisters;
    }

    public function addCashRegister(CashRegister $cashRegister): static
    {
        if (!$this->cashRegisters->contains($cashRegister)) {
            $this->cashRegisters->add($cashRegister);
            $cashRegister->setCompany($this);
        }

        return $this;
    }

    public function removeCashRegister(CashRegister $cashRegister): static
    {
        if ($this->cashRegisters->removeElement($cashRegister)) {
            // set the owning side to null (unless already changed)
            if ($cashRegister->getCompany() === $this) {
                $cashRegister->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Partner>
     */
    public function getPartners(): Collection
    {
        return $this->partners;
    }

    public function addPartner(Partner $partner): static
    {
        if (!$this->partners->contains($partner)) {
            $this->partners->add($partner);

templates/company/base.html.twig
{% extends 'base.html.twig' %}

{% trans_default_domain 'app' %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-5">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-user me-2"></i>{{ user.username }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a href="{{ path('change_password') }}" class="dropdown-item" href="#"><i class="fa-solid fa-lock me-2"></i> {{ 'general.change-password'|trans|lower }}</a></li>
                    <li><a href="{{ path('app_logout') }}" class="dropdown-item" href="#"><i class="fa-solid fa-right-from-bracket me-2"></i>{{ 'general.logout'|trans }}</a></li>
                </ul>
            </li>
        </ul>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if company.isConfigured and company.isActive %}
            <ul class="navbar-nav">
                <li class="nav-item ms-4">
                    <a class="nav-link" href="{{ path('company_info') }}"><i class="fa-solid fa-file-invoice me-2"></i>{{ 'company.nav.company'|trans }}</a>
                </li>
                <li class="nav-item ms-4">
                    <a class="nav-link" href="{{ path('company_partners') }}"><i class="fa-solid fa-warehouse me-2"></i>{{ 'company.nav.partners'|trans }}</a>
                </li>
                <li class="nav-item ms-4">
                    <a class="nav-link" href="{{ path('company_articles') }}"><i class="fa-solid fa-cart-shopping me-2"></i>{{ 'company.nav.articles'|trans }}</a>
                </li>
                <li class="nav-item ms-4">
                    <a class="nav-link" href="{{ path('company_categories') }}"><i class="fa-solid fa-list me-2"></i>{{ 'company.nav.categories'|trans }}</a>
                </li>
                {% if company.category.title == 'restaurant' %}
                <li class="nav-item ms-4">
                    <a class="nav-link" href="{{ path('company_tables') }}"><i class="fa-solid fa-chair me-2"></i>{{ 'company.nav.tables-layout'|trans }}</a>
                </li>
                {% endif %}
                <li class="nav-item ms-4">
                    <a class="nav-link" href="{{ path('company_bill') }}"><i class="fa-solid fa-receipt me-2"></i>{{ 'company.nav.bills'|trans }}</a>
                </li>
                <li class="nav-item ms-4">
                    <a class="nav-link" href="{{ path('company_analytics_review') }}"><i class="fa-solid fa-chart-pie me-2"></i>{{ 'company.nav.analytics'|trans }}</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% include 'footer.html.twig' %}
{% endblock %}

templates/company/change-password.html.twig
{% extends 'company/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
    <div class="container-fluid d-flex justify-content-center">
        <div class="admin-customer-registration-container">
            <div class="company-registration-form">
                <h3>{{ 'general.change-password'|trans }}</h3>
                <hr>
                {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
                {{ form_end(form) }}
            </div>
        </div>
    </div>

{% endblock %}

templates/company/edit-bank-accounts.html.twig
{% extends 'company/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
    <div class="container-fluid d-flex justify-content-center">
        <div class="company-form-collection-container">
            <div class="company-registration-form">
                <a class="back" href="{{ path('company_info') }}"><i class="fa-solid fa-arrow-left me-2"></i>{{ 'general.back'|trans }}</a>
                <hr>
                {{ form_start(form) }}

                {% if noBankAccounts %}
                    <ul class="item">
                        <li>
                            {{ 'errors.no-bank-accounts'|trans }}
                        </li>
                    </ul>
                {% endif %}
                <h5>{{ 'form.element.bank-accounts'|trans }}</h5>
                <ul class="bank_accounts"
                    data-index="{{ form.bank_accounts|length > 0 ? form.bank_accounts|last.vars.name + 1 : 0 }}"
                    data-prototype="{{ form_widget(form.bank_accounts.vars.prototype)|e('html_attr') }}"
                >
                    {% for account in form.bank_accounts %}
                        <li class="item">
                            {{ form_widget(account) }}
                        </li>
                    {% endfor %}
                </ul>

                <button type="button" class="add_item_link btn btn-sm btn-primary" data-collection-holder-class="bank_accounts">{{ 'form.element.add.bank-account'|trans }}</button>

                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js" integrity="sha512-GWzVrcGlo0TxTRvz9ttioyYJ+Wwk9Ck0G81D+eO63BaqHaJ3YZX9wuqjwgfcV/MrB2PhaVX9DkYVhbFpStnqpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        window.onload = function (e)
        {
            document
                .querySelectorAll('.add_item_link')
                .forEach(btn => {
                    btn.addEventListener("click", addFormToCollection)
                });

            document
                .querySelectorAll('ul.bank_accounts li.item')
                .forEach((tag) => {
                    addTagFormDeleteLink(tag)
                })
        }


        function addFormToCollection(e) {
            const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);

            const item = document.createElement('li');

            item.innerHTML = collectionHolder
                .dataset
                .prototype
                .replace(
                    /__name__/g,
                    collectionHolder.dataset.index
                );

            collectionHolder.appendChild(item);

            collectionHolder.dataset.index++;

            addTagFormDeleteLink(item);
        }

        function addTagFormDeleteLink(item) {
            const removeFormButton = document.createElement('button');
            removeFormButton.className = 'btn btn-danger btn-sm'
            removeFormButton.innerText = '{{ 'general.remove'|trans }}';

            item.append(removeFormButton);

            removeFormButton.addEventListener('click', (e) => {
                e.preventDefault();
                // remove the li for the tag form
                item.remove();
            });
        }
    </script>
{% endblock %}

templates/company/edit-cash-registers.html.twig
{% extends 'company/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
    <div class="container-fluid d-flex justify-content-center">
        <div class="company-form-collection-container">
            <div class="company-registration-form">
                <a class="back" href="{{ path('company_info') }}"><i class="fa-solid fa-arrow-left me-2"></i>{{ 'general.back'|trans }}</a>
                <hr>
                {{ form_start(form) }}

                {% if noCashRegisters %}
                    <ul class="item">
                        <li>
                            {{ 'errors.no-cash-registers'|trans }}
                        </li>
                    </ul>
                {% endif %}
                <h5>{{ 'form.element.cash-registers'|trans }}</h5>
                <ul class="cash_registers"
                    data-index="{{ form.cash_registers|length > 0 ? form.cash_registers|last.vars.name + 1 : 0 }}"
                    data-prototype="{{ form_widget(form.cash_registers.vars.prototype)|e('html_attr') }}"
                >
                    {% for cashRegister in form.cash_registers %}
                        <li class="item">
                            {{ form_widget(cashRegister) }}
                        </li>
                    {% endfor %}
                </ul>

                <button type="button" class="add_item_link btn btn-sm btn-primary" data-collection-holder-class="cash_registers">{{ 'form.element.add.cash-register'|trans }}</button>

                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js" integrity="sha512-GWzVrcGlo0TxTRvz9ttioyYJ+Wwk9Ck0G81D+eO63BaqHaJ3YZX9wuqjwgfcV/MrB2PhaVX9DkYVhbFpStnqpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        window.onload = function (e)
        {
            document
                .querySelectorAll('.add_item_link')
                .forEach(btn => {
                    btn.addEventListener("click", addFormToCollection)
                });

            document
                .querySelectorAll('ul.cash_registers li.item')
                .forEach((tag) => {
                    addTagFormDeleteLink(tag)
                })
        }


        function addFormToCollection(e) {
            const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);

            const item = document.createElement('li');

            item.innerHTML = collectionHolder
                .dataset
                .prototype
                .replace(
                    /__name__/g,
                    collectionHolder.dataset.index
                );

            collectionHolder.appendChild(item);

            collectionHolder.dataset.index++;

            addTagFormDeleteLink(item);
        }

        function addTagFormDeleteLink(item) {
            const removeFormButton = document.createElement('button');
            removeFormButton.className = 'btn btn-danger btn-sm'
            removeFormButton.innerText = '{{ 'general.remove'|trans }}';

            item.append(removeFormButton);

            removeFormButton.addEventListener('click', (e) => {
                e.preventDefault();
                // remove the li for the tag form
                item.remove();
            });
        }
    </script>
{% endblock %}

templates/company/edit-company.html.twig
{% extends 'company/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
    <div class="container-fluid d-flex justify-content-center">
        <div class="admin-customer-registration-container">
            <div class="company-registration-form">
                <a class="back" href="{{ path('company_info') }}"><i class="fa-solid fa-arrow-left me-2"></i>{{ 'general.back'|trans }}</a>
                <hr>
                {{ form_start(form) }}

                {{ form_row(form.title) }}
                {{ form_row(form.street) }}
                {{ form_row(form.number) }}
                {{ form_row(form.post_code) }}
                {{ form_row(form.city) }}
                {{ form_row(form.country) }}
                {{ form_row(form.tin) }}
                {{ form_row(form.identification_number) }}
                {{ form_row(form.vat) }}
                {{ form_row(form.category) }}
                {{ form_row(form.activity_code) }}
                <label for="company_info_company_image" class="required">{{ 'form.element.image'|trans }}</label>
                {{ form_row(form.image) }}

                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/company/edit-owner.html.twig
{% extends 'company/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
<div class="container-fluid d-flex justify-content-center">
    <div class="admin-customer-registration-container">
        <div class="company-registration-form">
            <a class="back" href="{{ path('company_info') }}"><i class="fa-solid fa-arrow-left me-2"></i>{{ 'general.back'|trans }}</a>
            <hr>
            {{ form(form) }}
        </div>
    </div>
</div>
{% endblock %}

templates/company/info.html.twig
{% extends 'company/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-12 col-lg-4">
            <h3 style="display: flex; justify-content: space-between;">{{ 'company.info.owner'|trans }}<a style="text-decoration: none; color: #292b2c;" href="{{ path('company_edit_owner') }}"><i class="fa-solid fa-pen-to-square"></i></a></h3>
            <hr>
            <ul>
                <li>{{ ('form.element.first-name'|trans) ~ ': ' ~ company.firstName }}</li>
                <li>{{ ('form.element.last-name'|trans) ~ ': ' ~ company.lastName }}</li>
                <li>{{ ('form.element.username'|trans) ~ ': ' ~ user.username }}</li>
                <li>{{ ('form.element.email'|trans) ~ ': ' ~ company.email }}</li>
                <li>{{ ('form.element.phone'|trans) ~ ': ' ~ company.phone }}</li>
            </ul>
        </div>
        <div class="col-12 col-lg-8">
            <h3 style="display: flex; justify-content: space-between;">
                <p class="mb-0">{{ 'company.info.company'|trans }}
                    {% if company.category.title == 'shop' %}
                        <i class="fa-solid fa-basket-shopping ms-2"></i>
                    {% else %}
                        <i class="fa-solid fa-utensils ms-2"></i>
                    {% endif %}
                    {% if company.vat %}
                        <i class="fa-solid fa-coins ms-2"></i>
                    {% endif %}
                </p>
                <a style="text-decoration: none; color: #292b2c;" href="{{ path('company_edit_company')}}">
                    <i class="fa-solid fa-pen-to-square"></i>
                </a>
            </h3>
            <hr>
            <div class="company-info">
                <div class="info">
                    <ul>
                        <li>{{ 'form.element.title'|trans ~ ': ' ~ company.title}}</li>
                        <li>{{ 'form.element.address'|trans ~ ': ' ~ company.street ~ ' ' ~ company.number ~ ' ' ~ company.postCode ~ ' ' ~ company.city ~ ' ' ~ company.country }}</li>
                        <li>{{ 'form.element.tin'|trans ~ ': ' ~ company.tin}}</li>
                        <li>{{ 'form.element.identification-number'|trans ~ ': ' ~ company.identificationNumber}}</li>
                        <li>{{ 'form.element.activity-code'|trans ~ ': ' ~ company.activityCode.code ~ ' - ' ~ company.activityCode.title}}</li>
                    </ul>
                </div>
                <div class="img">
                    <img alt="..." src="{{ '/' ~ company.logoUrl }}">
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        {% set cnt = 1 %}
        <div class="col-12 col-lg-4">
            <h3 style="display: flex; justify-content: space-between;">{{ 'company.info.bank-accounts'|trans }}<a style="text-decoration: none; color: #292b2c;" href="{{ path('company_edit_bank_accounts')}}"><i class="fa-solid fa-pen-to-square"></i></a></h3>
            <hr>
            <ul>
                {% for bankAccount in company.bankAccounts %}
                    <li>{{ cnt ~ '. ' ~ bankAccount.title }}</li>
                    {% set cnt = cnt + 1 %}
                {% endfor %}
            </ul>
        </div>
        {% set cnt = 1 %}
        <div class="col-12 col-lg-4">
            <h3 style="display: flex; justify-content: space-between;">{{ 'company.info.warehouses'|trans }}<a style="text-decoration: none; color: #292b2c;" href="{{ path('company_edit_warehouses')}}"><i class="fa-solid fa-pen-to-square"></i></a></h3>
            <hr>
            <ul>
                {% for warehouse in company.warehouses %}
                    <li>{{ cnt ~ '. ' ~ warehouse.code ~ ' - ' ~ warehouse.title }}</li>
                    {% set cnt = cnt + 1 %}
                {% endfor %}
            </ul>
        </div>
        {% set cnt = 1 %}
        <div class="col-12 col-lg-4">
            <h3 style="display: flex; justify-content: space-between;">{{ 'company.info.cash-registers'|trans }}<a style="text-decoration: none; color: #292b2c;" href="{{ path('company_edit_cash_registers')}}"><i class="fa-solid fa-pen-to-square"></i></a></h3>
            <hr>
            <ul>
                {% for cashRegister in company.cashRegisters %}
                    <li>{{ cnt ~ '. ' ~ cashRegister.location ~ ' - ' ~ cashRegister.type.title }}</li>
                    {% set cnt = cnt + 1 %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/company/not-active.html.twig
{% extends 'company/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
    <div class="container py-5">
        <h1 class="text-center"><i class="fa-solid fa-triangle-exclamation me-3"></i>{{ 'company.inactive'|trans }}<i class="fa-solid fa-triangle-exclamation ms-3"></i></h1>
    </div>
{% endblock %}