src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $code = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $unit = null;

    #[ORM\ManyToOne]
    private ?TaxRateType $tax_rate_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $producer = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?ArticleType $article_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_url = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?ArticleCategory $article_category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $foreign_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $barcode = null;

//    #[ORM\Column(length: 255, nullable: true)]
//    private ?string $producer_title = null;

    #[ORM\Column(nullable: true)]
    private ?int $customs_tariff = null;

    #[ORM\Column(nullable: true)]
    private ?bool $eco_tax = null;

    #[ORM\Column(nullable: true)]
    private ?bool $excise_tax = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $declaration = null;

    #[ORM\OneToMany(targetEntity: ArticleWarehouse::class, mappedBy: 'article')]
    private Collection $articleWarehouses;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Company $company = null;

    #[ORM\Column(nullable: true)]
    private ?bool $active = null;

    #[ORM\Column(nullable: true)]
    private ?int $supplies_amount_max = null;

    #[ORM\Column(nullable: true)]
    private ?int $supplies_amount_min = null;

    public function __construct()
    {
        $this->articleWarehouses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getUnit(): ?string
    {
        return $this->unit;
    }

    public function setUnit(?string $unit): static
    {
        $this->unit = $unit;

        return $this;
    }

    public function getTaxRateType(): ?TaxRateType
    {
        return $this->tax_rate_type;
    }

    public function setTaxRateType(?TaxRateType $tax_rate_type): static
    {
        $this->tax_rate_type = $tax_rate_type;

        return $this;
    }

    public function getProducer(): ?string
    {
        return $this->producer;
    }

    public function setProducer(string $producer): static
    {
        $this->producer = $producer;

        return $this;
    }

    public function getArticleType(): ?ArticleType
    {
        return $this->article_type;
    }

    public function setArticleType(?ArticleType $article_type): static
    {
        $this->article_type = $article_type;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): static
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getArticleCategory(): ?ArticleCategory
    {
        return $this->article_category;
    }

    public function setArticleCategory(?ArticleCategory $article_category): static
    {
        $this->article_category = $article_category;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getForeignTitle(): ?string
    {
        return $this->foreign_title;
    }

    public function setForeignTitle(?string $foreign_title): static
    {
        $this->foreign_title = $foreign_title;

        return $this;
    }

    public function getBarcode(): ?string
    {
        return $this->barcode;
    }

    public function setBarcode(?string $barcode): static
    {
        $this->barcode = $barcode;

        return $this;
    }

//    public function getProducerTitle(): ?string
//    {
//        return $this->producer_title;
//    }
//
//    public function setProducerTitle(?string $producer_title): static
//    {
//        $this->producer_title = $producer_title;
//
//        return $this;
//    }

    public function getCustomsTariff(): ?int
    {
        return $this->customs_tariff;
    }

    public function setCustomsTariff(?int $customs_tariff): static
    {
        $this->customs_tariff = $customs_tariff;

        return $this;
    }

    public function isEcoTax(): ?bool
    {
        return $this->eco_tax;
    }

    public function setEcoTax(?bool $eco_tax): static
    {
        $this->eco_tax = $eco_tax;

        return $this;
    }

    public function isExciseTax(): ?bool
    {
        return $this->excise_tax;
    }

    public function setExciseTax(?bool $excise_tax): static
    {
        $this->excise_tax = $excise_tax;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDeclaration(): ?string
    {
        return $this->declaration;
    }

    public function setDeclaration(?string $declaration): static
    {
        $this->declaration = $declaration;

        return $this;
    }

    /**
     * @return Collection<int, ArticleWarehouse>
     */
    public function getArticleWarehouses(): Collection
    {
        return $this->articleWarehouses;
    }

    public function addArticleWarehouse(ArticleWarehouse $articleWarehouse): static
    {
        if (!$this->articleWarehouses->contains($articleWarehouse)) {
            $this->articleWarehouses->add($articleWarehouse);
            $articleWarehouse->setArticle($this);
        }

        return $this;
    }

    public function removeArticleWarehouse(ArticleWarehouse $articleWarehouse): static
    {
        if ($this->articleWarehouses->removeElement($articleWarehouse)) {
            // set the owning side to null (unless already changed)
            if ($articleWarehouse->getArticle() === $this) {
                $articleWarehouse->setArticle(null);
            }
        }

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function getSuppliesAmountMax(): ?int
    {
        return $this->supplies_amount_max;
    }

    public function setSuppliesAmountMax(?int $supplies_amount_max): static
    {
        $this->supplies_amount_max = $supplies_amount_max;

        return $this;
    }

    public function getSuppliesAmountMin(): ?int
    {
        return $this->supplies_amount_min;
    }

    public function setSuppliesAmountMin(?int $supplies_amount_min): static
    {
        $this->supplies_amount_min = $supplies_amount_min;

        return $this;
    }
}

src/Entity/ArticleType.php
<?php

namespace App\Entity;

use App\Repository\ArticleTypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleTypeRepository::class)]
class ArticleType
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'article_type')]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setArticleType($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getArticleType() === $this) {
                $article->setArticleType(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->title;
    }
}

templates/article/articles.html.twig
{% extends 'company/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
    <div class="container py-5">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <h3>{{ 'company.nav.articles'|trans }} {% if totalRows > 0 %} ({{ totalRows ~ ' ' ~ 'articles.message.total-rows'|trans }}) {% endif %}</h3>
                    </div>
                    <div class="col-6 text-end">
                        <a href="{{ path('company_articles_edit') }}" class="btn btn-primary">{{ 'articles.add-new'|trans }}</a>
                    </div>
                </div>
                <hr>
                <div class="table-responsive">
                    {% if table %}
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">{{ 'articles.table.logo'|trans }}</th>
                                <th scope="col">{{ 'articles.table.code'|trans }}</th>
                                <th scope="col">{{ 'articles.table.title'|trans }}</th>
                                <th scope="col">{{ 'articles.table.unit'|trans }}</th>
                                <th scope="col">{{ 'articles.table.tax-rate'|trans }} [%]</th>
                                <th scope="col">{{ 'articles.table.producer'|trans }}</th>
                                <th class="text-center" scope="col">{{ 'articles.table.edit'|trans }}</th>
                                <th class="text-center" scope="col">{{ 'articles.table.remove'|trans }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for row in table %}
                                <tr>
                                    <td><img width="50px;" src="{% if row.imageUrl %} {{'/' ~ row.imageUrl }} {% else %} /server_simulation/defaults/default.png {% endif %}" alt="..."></td>
                                    <td>{{ row.code }}</td>
                                    <td>{{ row.title }}</td>
                                    <td>{{ row.unit }}</td>
                                    <td>{% if row.taxRateType %}{{ row.taxRateType.value }}{% else %}0{% endif %}</td>
                                    <td>{{ row.producer }}</td>
                                    <td class="text-center"><a href="{{ path('company_articles_edit', {id: row.id}) }}" class="btn btn-success"><i class="fa-solid fa-pen-to-square"></i></a></td>
                                    <td class="text-center"><button onclick="setArticleValue({{ row.id }}, '{{ row.title }}')" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="fa-solid fa-trash"></i></button></td>
                                    {#                                    <td class="text-center"><a href="#" class="btn btn-danger"><i class="fa-solid fa-trash"></i></a></td>#}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        {{ 'general.empty-category'|trans }}
                    {% endif %}
                </div>
            </div>
        </div>

        {% if totalPages > 1 %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a class="page-link {% if currentPage == 1 %} disabled {% endif %}" href="{{ path('company_articles', {page: currentPage - 1}) }}"><i class="fa-solid fa-square-caret-left"></i></a></li>
                {% for page in 1..totalPages %}
                    <li class="page-item"><a class="page-link {% if page == currentPage %} active {% endif %}" href="{{ path('company_articles', {page: page}) }}">{{ page }}</a></li>
                {% endfor %}
                <li class="page-item"><a class="page-link {% if currentPage == totalPages %} disabled {% endif %}" href="{{ path('company_articles', {page: currentPage + 1}) }}"><i class="fa-solid fa-square-caret-right"></i></a></li>
            </ul>
        </nav>
        {% endif %}
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{ 'general.deleting-article'|trans }} "<b id="article-name"></b>".</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="overflow-y: scroll;">
                    <input id="article-value" type="hidden" value="0">
                    <p>{{ 'general.delete-the-item'|trans }} <b id="article-title"></b>?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ 'general.close'|trans }}</button>
                    <button onclick="goToRoute()" type="button" class="btn btn-primary">{{ 'general.remove'|trans }}</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js" integrity="sha512-GWzVrcGlo0TxTRvz9ttioyYJ+Wwk9Ck0G81D+eO63BaqHaJ3YZX9wuqjwgfcV/MrB2PhaVX9DkYVhbFpStnqpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        function setArticleValue(id, title)
        {
            document.getElementById('article-value').value = id;
            document.getElementById('article-name').innerHTML = title;
            document.getElementById('article-title').innerHTML = title;
        }

        function goToRoute()
        {
            window.location = '/company/articles/remove/' + document.getElementById('article-value').value;
        }
    </script>
{% endblock %}

templates/article/edit.html.twig
{% extends 'company/base.html.twig' %}

{% trans_default_domain 'app' %}

{% block content %}
<div class="admin-company-registration-container">
    <div class="company-registration-form">

        <div class="container-fluid p-0 m-0">
            <div class="row">
                <div class="col-6">
                    <h1>{{ 'general.new-article'|trans }}</h1>
                </div>
                <div class="col-6 text-end">
                    <a class="back" href="{{ path('company_articles') }}"><i class="fa-solid fa-arrow-left me-2"></i>{{ 'general.back'|trans }}</a>
                </div>
            </div>

            <hr>

            {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}

            <h3>{{ 'articles.message.general-data'|trans }}</h3>
            <hr>

            <div class="row">
                <div class="col-12 col-md-6">
                    {{ form_row(form.code) }}
                </div>
                <div class="col-12 col-md-6">
                    {{ form_row(form.title) }}
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-6">
                    {{ form_row(form.unit) }}
                </div>
                <div class="col-12 col-md-6">
                    {% if company.vat %}
                        {{ form_row(form.tax_rate_type) }}
                    {% else %}
                        {{ form_row(form.tax_rate_type, {disabled: 'disabled'}) }}
                    {% endif %}
                </div>
            </div>

            {% if company.category.title == 'restaurant' %}
            <div class="row">
                <div class="col">
                    {{ form_row(form.article_type) }}
                </div>
            </div>
            {% endif %}

            <h3>{{ 'articles.message.additional-data'|trans }}</h3>
            <hr>

            <div class="row">
                <div class="col-12 col-md-6">
                    {{ form_row(form.producer) }}
                </div>
                <div class="col-12 col-md-6">
                    {{ form_row(form.country) }}
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-6">
                    {{ form_row(form.foreign_title) }}
                </div>
                <div class="col-12 col-md-6">
                    {{ form_row(form.barcode) }}
                </div>
            </div>

{#            <div class="row">#}
{#                <div class="col-12 col-md-6">#}
{#                    {{ form_row(form.producer_title) }}#}
{#                </div>#}
{#            </div>#}

            <div class="row">
                <div class="col-12">
                    {{ form_row(form.description) }}
                </div>
                <div class="col-12">
                    {{ form_row(form.declaration) }}
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-4">
                    {{ form_row(form.customs_tariff) }}
                </div>
                <div class="col-12 col-md-4">
                    {{ form_row(form.supplies_amount_min) }}
                </div>
                <div class="col-12 col-md-4">
                    {{ form_row(form.supplies_amount_max) }}
                </div>
            </div>

            {{ form_row(form.eco_tax) }}

            {{ form_row(form.excise_tax) }}

            <label for="article_form_image">{{ 'form.element.image'|trans }}</label>
            {{ form_row(form.image) }}


            <h3 class="mt-3">{{ 'articles.message.prices-and-warehouses'|trans }}</h3>
            <hr>

            {% for warehouse in company.warehouses %}
                <h5>{{ warehouse.title ~ ' - ' ~warehouse.code }}</h5>
                <hr>
                <div class="row">
                    <div class="col-12 col-md-6">
                        {{ form_row(form['warehouse_buying_price_' ~ warehouse.id]) }}
                    </div>
                    <div class="col-12 col-md-6">
                        {{ form_row(form['warehouse_selling_price_' ~ warehouse.id]) }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-md-4">
                        {{ form_row(form['warehouse_amount_current_' ~ warehouse.id]) }}
                    </div>
                    <div class="col-12 col-md-4">
                        {{ form_row(form['warehouse_amount_min_' ~ warehouse.id]) }}
                    </div>
                    <div class="col-12 col-md-4">
                        {{ form_row(form['warehouse_amount_max_' ~ warehouse.id]) }}
                    </div>
                </div>
            {% endfor %}

            {{ form_row(form.submit) }}

            {{ form_end(form, {render_rest: false}) }}
        </div>
    </div>
</div>

{% endblock %}